name: Hellow World

on: [push]

jobs:
  build:
  
    runs-on: centos-latest
    
    steps:
    #- uses: actions/checkout@v2
    - name: Run pwd
      run: pwd
    - name: Run ls -al
      run: ls -al
